user nginx;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log warn;

include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 8192;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    access_log /var/log/nginx/access.log;
    include /etc/nginx/conf.d/*.conf;
}

rtmp {
    include /etc/nginx/rtmp-conf.d/*.conf;
}

stream {
    include /etc/nginx/stream-conf.d/*.conf;
}
