server {
    listen 80;
    listen [::]:80;
    server_name iptv.nyist.edu.cn;
    root /usr/local/nginx/html/iptv;
    include /etc/nginx/snippets/iptv-hls.conf;
    include /etc/nginx/snippets/iptv-sensitive-endpoints.conf;
}
